---
- name: Prepare tmp directory for credentials on ansible runner
  ansible.builtin.file:
    path: "{{ __ansible_runner_tmp_credentials_path }}"
    state: directory
    mode: "0755"
  delegate_to: localhost

- name: Fetch concrete '{{ _rin__certificate_type }}' credentials from server to ansible master
  ansible.builtin.fetch:
    src: "{{ __pki_path }}{{ item }}"
    dest: "{{ __ansible_runner_tmp_credentials_path }}"
    flat: true
  with_items:
    - "issued/{{ __certificate_source_name }}.crt"
    - "private/{{ __certificate_source_name }}.key"
  delegate_to: "{{ __vpn_server_ip }}"
  become: true

- name: Create VPN certificate folder on target
  ansible.builtin.file:
    path: "/etc/openvpn/cartken/2.0/crt/"
    state: directory
    mode: "0755"
  become: true

- name: Copy concrete '{{ _rin__certificate_type }}' credentials from ansible master to target and rename them to fit VPN config
  ansible.builtin.copy:
    src: "{{ item.src }}"
    # We need to rename the files to fit the generic vpn config e.g. instead of 'cart26.crt' we need 'robot.crt'
    dest: "/etc/openvpn/cartken/2.0/crt/{{ item.dest }}"
    mode: "0644"
  with_items:
    - { src: "{{ __ansible_runner_tmp_credentials_path }}{{ __certificate_source_name }}.crt", dest: "{{ __certificate_target_name }}.crt" }
    - { src: "{{ __ansible_runner_tmp_credentials_path }}{{ __certificate_source_name }}.key", dest: "{{ __certificate_target_name }}.key" }
    # part of the IT-Management repo
    - { src: "ca.crt", dest: "ca.crt" }
    - { src: "ta.key", dest: "ta.key" }
  become: true

- name: Delete tmp credential directory on ansible master
  ansible.builtin.file:
    path: "{{ __ansible_runner_tmp_credentials_path }}"
    state: absent
  delegate_to: localhost
