---

- name: Install auxiliary packages
  become: true
  ansible.builtin.apt:
    pkg:
      - vim
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - make
      - tree
      - neofetch
      - bat
      - ripgrep
    state: latest
    update_cache: true
