---
- name: Add Testbed-Machines Inventory
  block:
    - awx.awx.inventory:
        name: testbed-machines
        organization: SPEAR
        state: present

    - awx.awx.inventory_source:
        name: spear-testbed-repo
        state: present
        source: scm
        source_project: spear-testbed-repo
        source_path: inventories/hosts
        inventory: testbed-machines
        # Refresh inventory data from its source each time a job is run.
        update_on_launch: false
        organization: SPEAR

    - name: Update the inventory source to ensure latest inventory use.
      awx.awx.inventory_source_update:
        name: spear-testbed-repo
        inventory: testbed-machines
        organization: SPEAR
