---
- name: Configure every cluster aspect except playbook related parts
  when: not _rin__only_update_playbook_related
  block:
    - ansible.builtin.include_tasks: tasks/organizations/apply.yml

    - ansible.builtin.include_tasks: credential_types.yml

    - ansible.builtin.include_tasks: tasks/credentials/apply.yml

    - ansible.builtin.include_tasks: tasks/teams/apply.yml

    - ansible.builtin.include_tasks: tasks/users/apply.yml

    - ansible.builtin.include_tasks: tasks/projects/apply.yml

    - ansible.builtin.include_tasks: tasks/inventories/apply.yml

    - ansible.builtin.include_tasks: tasks/execution_environments/apply.yml

    - ansible.builtin.include_tasks: instance_groups.yml

    - ansible.builtin.include_tasks: tasks/settings/apply.yml

- ansible.builtin.include_tasks: tasks/templates/apply.yml

- ansible.builtin.include_tasks: tasks/roles/apply.yml
