---
- name: Add VPN clients
  hosts: cloud-server
  vars:
    usernames:
      - malyuk_alexander
  tasks:
    - name: Run OpenVPN client build for each user
      ansible.builtin.include_role:
        name: cloud-server/vpn/add-client
      vars:
        _rin__clientname: "{{ item }}"
      loop: "{{ usernames }}"
