---
- name: Check that all required variables are set
  hosts: localhost
  roles:
    - role: common/check-required-variables
      _rin__required_variables:
        - client_names
        - copy_over_credentials_to_localhost

- name: Add VPN users (dynamic IPs)
  hosts: cloud-server
  vars:
    copy_credentials_to_localhost: "{{ copy_over_credentials_to_localhost | bool }}"
  tasks:
    - name: Run OpenVPN client build for each user
      ansible.builtin.include_role:
        name: cloud-server/vpn/add-client
      vars:
        _rin__client_name: "{{ item }}"
      loop: "{{ client_names }}"

    - name: Retrieve all new client certificates
      ansible.builtin.include_role:
        name: cloud-server/vpn/get-client-credentials
      vars:
        _rin__client_name: "{{ item }}"
        _rin__copy_to_localhost: "{{ copy_credentials_to_localhost }}"
      loop: "{{ client_names }}"
