---

# Intended to be run on an administrator's work machine, not AWX.

# We use a single dockerized OpenVPN server for our VPN.
# https://github.com/kylemanna/docker-openvpn/tree/master

- name: VPN Setup
  hosts: cloud-server
  vars:
    common_name: "SPEAR-EDGE-TESTBED-VPN-Server"
    force_vpn_config_update: false

  roles:
    - role: cloud-server/vpn/setup
      _rin__force_vpn_config_update: "{{ force_vpn_config_update | bool }}"
