---
- name: Delete initial Demo Credential
  awx.awx.credential:
    name: Demo Credential
    credential_type: Machine
    state: absent

- name: Ensure testbed git repository access credentials exist
  block:
    - name: Ensure testbed repository read access credential
      awx.awx.credential:
        name: "{{ __testbed_read_repository_credential_name }}"
        credential_type: Source Control
        state: present
        organization: SPEAR
        inputs:
          username: "{{ testbed_read_repo_deploy_token_name }}"
          password: "{{ testbed_read_repo_deploy_token_pwd }}"

    - name: Ensure testbed image registry read access credential
      awx.awx.credential:
        name: "{{ __testbed_read_image_registry_credential_name }}"
        credential_type: Container Registry
        state: present
        organization: SPEAR
        inputs:
          username: "{{ testbed_read_image_registry_deploy_token_name }}"
          password: "{{ testbed_read_image_registry_deploy_token_pwd }}"
          host: ghcr.io

- name: "Ensure the initial machine password credentials exist"
  awx.awx.credential:
    name: Initial machine password
    credential_type: Initial machine password
    state: present
    organization: SPEAR
    inputs:
      password: "{{ init_machine_password }}"
#
# - name: "Ensure Pi root access credentials exist"
#   awx.awx.credential:
#     name: Pi root access
#     credential_type: Machine
#     state: present
#     organization: SPEAR
#     description: machine access
#     inputs:
#       become_method: sudo
#       become_username: root
#       become_password: "{{ privilege_escalation_password }}"
