---
- name: "GET all credentials"
  ansible.builtin.set_fact:
    credentials: >
      {{ query('awx.awx.controller_api',
          'credentials',
          host=env_vars.CONTROLLER_HOST,
          verify_ssl=env_vars.CONTROLLER_VERIFY_SSL,
          username=env_vars.CONTROLLER_USERNAME,
          password=env_vars.CONTROLLER_PASSWORD,
          all_pages=True)
      | rejectattr('name', 'equalto', 'Ansible Galaxy')
      | list }}

- awx.awx.credential:
    name: "{{ item.name }}"
    credential_type: "{{ item.credential_type }}"
    state: absent
  loop: "{{ credentials }}"
