---

- name: Add prometheus-community Helm repo
  community.kubernetes.helm_repository:
    repo_name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  changed_when: "'Update Complete.' in repo_update.stdout"
  register: repo_update

- name: Create 'prometheus' namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: prometheus
    state: present

- name: Install kube-prometheus-stack chart
  community.kubernetes.helm:
    release_name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: prometheus
    create_namespace: false
    values: {}
    state: present
