---

- hosts: localhost
  gather_facts: false
  vars_files:
    - "files/awx_cluster_access_credentials.yml"
  environment: "{{ env_vars }}"
  roles:
    - role: awx/sync-awx-project
      _rin__branch: "{{ branch | default('master') }}"
