---
# Intended to be run on an administrator's work machine, not AWX.

# IMPORTANT: Ensure that the ansible-galaxy roles are installed on the ansible-host that will run this playbook.
# To install these requirements run "make install-ansible-requirements" in the root of the test-bed repository.

- name: Initial Setup
  hosts: cloud-server

  pre_tasks:
    - name: Update apt cache and upgrade packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

  roles:
    - role: common/install-aux-tools
    - role: third-party/geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_install_compose_plugin: true
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present
    - role: third-party/gantsign.golang
