---

- name: K3S AWX Setup
  hosts: cloud-server
  environment:
    # NOTE: K3S has a unique location for its kubectl file.
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  vars:
    k3s_release_version: v1.29.6+k3s2
    k3s_become: true
    k3s_build_cluster: false
    k3s_server:
      write-kubeconfig-mode: "644"
      bind-address: "{{ cloud_server_ip }}"
      tls-san: "{{ cloud_server_ip }}"
      # disable:
      #   # IMPORTANT: If issues reaching AWX should occur - try removing this
      #   - traefik

  pre_tasks:
    - name: Install python3-kubernetes package
      ansible.builtin.apt:
        name: python3-kubernetes
        update_cache: true
      become: true

  roles:
    - role: third-party/xanmanning.k3s
    - role: third-party/gantsign.helm
    - role: cloud-server/install-prometheus
    - role: cloud-server/setup-awx-operator
