---

# IMPORTANT: Ensure that the ansible-galaxy roles are installed on the ansible-host that will run this playbook.
# To install these requirements run "make install-ansible-requirements" in the root of the test-bed repository.

- name: K3S AWX Setup
  hosts: cloud-server
  vars:
    # k3s_release_version: v1.32.3+k3s1
    k3s_release_version: v1.29.6+k3s2
    k3s_become: true
    # Ensures standalone (not a cluster)
    k3s_build_cluster: false
    k3s_server:
      write-kubeconfig-mode: "644"
      bind-address: "{{ cloud_server_ip }}"
      tls-san: "{{ cloud_server_ip }}"
      # disable:
      #   # IMPORTANT: If issues reaching AWX should occur - try removing this
      #   - traefik
  roles:
    # Install & set up K3S
    - role: third-party/xanmanning.k3s
    # Install helm
    - role: third-party/gantsign.helm
    # Install prometheus for cluster metrics
    - role: cloud-server/install-prometheus
