---
- name: VPN Setup
  hosts: cloud-server
  vars:
    vpn_image: kylemanna/openvpn
    ovpn_data_volume_name: ovpn-data-spear
    ovpn_data_volume_path: /var/lib/docker/volumes/ovpn-data-spear/_data/
    common_name: "SPEAR-EDGE-TESTBED-VPN-Server"
    update_vpn_config: false

  tasks:
    - name: Check if OpenVPN config exists
      ansible.builtin.stat:
        path: "{{ ovpn_data_volume_path }}/openvpn.conf"
      register: ovpn_config

    - name: Generate the OpenVPN config
      when: not ovpn_config.stat.exists or update_vpn_config
      block:

        - name: Generate OpenVPN config
          community.docker.docker_container:
            name: ovpn_genconfig
            image: "{{ vpn_image }}"
            command: ovpn_genconfig -c -d -N -u udp://{{ cloud_server_ip }}:{{ vpn_port }}
            volumes:
              - "{{ ovpn_data_volume_name }}:/etc/openvpn"
            auto_remove: true

        - name: Remove compression lines from OpenVPN config
          ansible.builtin.lineinfile:
            path: "{{ ovpn_data_volume_path }}/openvpn.conf"
            regexp: '^(comp-lzo no|push "comp-lzo no")$'
            state: absent
          become: true


    - name: Check if OpenVPN PKI CA exists
      ansible.builtin.stat:
        path: "{{ ovpn_data_volume_path }}/pki"
      register: ovpn_pki

    - name: Generate the PKI
      when: not ovpn_pki.stat.exists
      block:

        - name: Start OpenVPN container for PKI initiation
          community.docker.docker_container:
            name: ovpn_initpki
            image: "{{ vpn_image }}"
            command: sleep infinity
            volumes:
              - "{{ ovpn_data_volume_name }}:/etc/openvpn"
            env:
              EASYRSA_REQ_CN: "{{ common_name }}"
            auto_remove: false
            state: started

        - name: Run ovpn_initpki with expect for passphrase prompts
          ansible.builtin.expect:
            command: docker exec -i ovpn_initpki ovpn_initpki
            responses:
              'Enter New CA Key Passphrase:': "ca_pwd_todo"
              'Re-Enter New CA Key Passphrase:': "ca_pwd_todo"
              'Common Name \(eg: your user, host, or server name\) \[Easy-RSA CA\]': "{{ common_name }}"
              'Enter pass phrase for /etc/openvpn/pki/private/ca.key': "ca_pwd_todo"
            timeout: 300
          vars:
            ca_passphrase: "1234todo"
          no_log: false

        - name: Remove the OpenVPN PKI init container
          community.docker.docker_container:
            name: ovpn_initpki
            state: absent
            force_kill: true

    - name: Run OpenVPN Server
      community.docker.docker_container:
        name: openvpn
        image: kylemanna/openvpn
        detach: true
        published_ports:
          - "1194:1194/udp"
        volumes:
          - "{{ ovpn_data_volume_name }}:/etc/openvpn"
        capabilities:
          - NET_ADMIN


# -----------------------

    - name: Run OpenVPN client build in Docker
      ansible.builtin.expect:
        command: docker run -i -v {{ ovpn_data_volume_name }}:/etc/openvpn --rm kylemanna/openvpn easyrsa build-client-full TESTNUC nopass
        responses:
          'Enter pass phrase for /etc/openvpn/pki/private/ca.key': "ca_pwd_todo"
        timeout: 60
      no_log: false

    - name: Run OpenVPN client build in Docker
      ansible.builtin.expect:
        command: docker run -v {{ ovpn_data_volume_name }}:/etc/openvpn --rm kylemanna/openvpn ovpn_getclient TESTNUC separated
        responses:
          'Enter pass phrase for /etc/openvpn/pki/private/ca.key': "ca_pwd_todo"
        timeout: 60
      no_log: false
