---
- ansible.builtin.include_role:
    name: cluster/query-awx-cluster
  vars:
    _rin__query_target: "job_templates"

- awx.awx.job_template:
    name: "{{ item }}"
    state: absent
  loop: "{{ job_templates }}"
