---

- ansible.builtin.set_fact:
    archive_folder_path: "/tmp/vpn-client-credentials"

- ansible.builtin.set_fact:
    archive_path: "{{ archive_folder_path }}/{{ _rin__client_name }}.tar.gz"

- name: "Create client credentials folder for '{{ _rin__client_name }}'"
  become: true
  ansible.builtin.expect:
    command: >
      docker run
      -v {{ _gv__vpn_data_volume_name }}:/etc/openvpn
      --rm {{ _gv__vpn_image }}
      ovpn_getclient
      {{ _rin__client_name }}
      separated
    responses:
      "Enter pass phrase for /etc/openvpn/pki/private/ca.key": "{{ _gv__vpn_ca_pwd }}"
    timeout: 60
  no_log: false

- name: Ensure keepalive is present in client config
  become: true
  lineinfile:
    path: "{{ _gv__vpn_data_volume_path }}/clients/{{ _rin__client_name }}/{{ _rin__client_name }}.ovpn"
    regexp: '^keepalive '
    line: "keepalive 10 60"
    insertafter: EOF

- ansible.builtin.include_tasks: copy_to_localhost.yml
  when: _rin__copy_to_localhost
