---
_rin__only_update_playbook_related: false
_rin__reset_configuration: false

__state: "{{ 'absent' if _rin__reset_configuration else 'present' }}"

__admin_team: "Admins"
__user_team: "Users"

__all_teams:
  - "{{ __admin_team }}"
  - "{{ __user_team }}"

__testbed_read_repository_credential_name: testbed git

__testbed_read_image_registry_credential_name: Default Execution Environment Registry Credential

__latest_ee_name: latest_EE

__github_docker_deploy_access_credential_type_name: Github docker deploy access
__awx_docker_deb_deploy_token_credential_name: awx-docker-deb-deploy-token

__github_api_read_token_credential_type_name: GitHub testbed API read token
__github_api_read_token_credential_name: GitHub testbed API read token

__default_container_group: Default Pod
