---
- name: Check that all required variables are set
  hosts: localhost
  roles:
    - role: common/check-required-variables
      _rin__required_variables:
        - copy_over_credentials_to_localhost

- name: Add master NUC
  hosts: cloud-server
  vars:
    master_nuc_common_name: "master_nuc"
    copy_credentials_to_localhost: "{{ copy_over_credentials_to_localhost | bool }}"
  tasks:

    - name: Run OpenVPN client build
      ansible.builtin.include_role:
        name: local/cloud-server/vpn/add-client
      vars:
        _rin__client_name: "{{ master_nuc_common_name }}"
        _rin__static_ip: "{{ _gv__master_nuc_vpn_ip }}"

    - name: Retrieve credentials
      ansible.builtin.include_role:
        name: local/cloud-server/vpn/get-client-credentials
      vars:
        _rin__client_name: "{{ master_nuc_common_name }}"
        _rin__copy_to_localhost: "{{ copy_credentials_to_localhost }}"
