---
# We use a single dockerized OpenVPN server for our VPN.
# https://github.com/kylemanna/docker-openvpn/tree/master

- name: VPN Setup
  hosts: cloud-server
  vars:
    common_name: "SPEAR-EDGE-TESTBED-VPN-Server"
    force_vpn_config_update: false
    cloud_server_common_name: cloud_server
    vpn_client_service: "openvpn-client@cloud_server"

  roles:
    - role: local/cloud-server/vpn/setup
      _rin__force_vpn_config_update: "{{ force_vpn_config_update | bool }}"
