---
# TODO: Evaluate & Discuss if we need all of those custom credential types or if we can replace them via already pre-build AWX credential types.
# NOTE: AWX comes with several pre-configured credential-types.
# Instead of GETting all of them and filtering this large set we simply set custom ones to absent.

- awx.awx.credential_type:
    name: "{{ __github_docker_deploy_access_credential_type_name }}"
    # NOTE: This type seems to be used for custom credentials.
    kind: cloud
    inputs:
      fields:
        - id: github_user
          type: string
          label: Username
          secret: true
        - id: github_token
          type: string
          label: Password
          secret: true
      required:
        - github_user
        - github_token
    injectors:
      # NOTE: We want to have the unresolved variable notion here.
      extra_vars:
        github_registry_user: "{% raw %}{{ github_user }}{% endraw %}"
        github_registry_token: "{% raw %}{{ github_token }}{% endraw %}"
    state: "{{ __state }}"

- awx.awx.credential_type:
    name: "{{ __github_api_read_token_credential_type_name }}"
    kind: cloud
    inputs:
      fields:
        - id: token
          type: string
          label: Token
          secret: true
      required:
        - token
    injectors:
      extra_vars:
        github_api_read_token: "{% raw %}{{ token }}{% endraw %}"
    state: "{{ __state }}"

- awx.awx.credential_type:
    name: Initial machine password
    description: The initial machine password as an ansible variable 'init_machine_password'.
    kind: cloud
    inputs:
      fields:
        - id: password
          type: string
          label: Password
          secret: true
      required:
        - password
    injectors:
      extra_vars:
        init_machine_password: "{% raw %}{{ password }}{% endraw %}"
    state: "{{ __state }}"
